version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.13
  build:
    commands:
      - go build -o goapp
artifacts:
  files:
    - goapp
    - appspec.yml
    - buildspec.yml
    - hooks/*
