version: "3"

services:
  mysql:
    image: mysql:5.7.29
    container_name: ay1st_mysql_local
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: Asia/Tokyo
    ports:
      - 9306:3306
    volumes:
      - ay1st-mysql:/var/lib/mysql
      - ./fixtures:/var/fixtures/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD:
    ports:
      - 9180:80
    depends_on:
      - mysql

volumes:
  ay1st-mysql:
